spring:
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      loadbalancer:
        use404: true # 当你通过lb访问一个不存的服务时（例如：hello-service1），会返回404（默认是503）
      routes:
        - id: hello-service
          uri: lb://hello-service # 负载均衡
          predicates:
            - Path=/hello
        - id: hello-service1
          uri: lb://hello-service1
          predicates:
            - Path=/hello1
    discovery:
      client:
        # 静态服务配置，SimpleDiscoveryClient
        simple:
          instances:
            hello-service:
              - uri: http://localhost:8001
                instance-id: s1
              - uri: http://localhost:8002
                instance-id: s2
              - uri: http://localhost:8003
                instance-id: s3