spring:
  cloud:
    loadbalancer:
      cache:
        enabled: false
      enabled: true
    gateway:
      loadbalancer:
        use404: true # 当你通过lb访问一个不存的服务时（例如：hello-service1），会返回404（默认是503）
      routes:
        - id: retryshortcut_route
          uri: https://httpspot.dev
          predicates:
            - Path=/status/**
          filters:
            - Retry=3,INTERNAL_SERVER_ERROR,GET,10ms,50ms,2,false
        #        - id: retry-with-cb
        #          uri: https://httpspot.dev
        #          predicates:
        #            - Path=/status/**
        #          filters:
        #            - Retry=3,INTERNAL_SERVER_ERROR,GET,10ms,50ms,2,false
        #            - name: CircuitBreaker
        #              args:
        #                name: myCircuitBreaker
        #                fallbackUri: forward:/fallback
        - id: fallback
          uri: http://localhost:8080
          predicates:
            - Path=/fallback
        - id: hello-service
          uri: lb://hello-service # 负载均衡
          predicates:
            - Path=/hello
          filters:
            #            - name: Retry
            #              args:
            #                retries: 3
            #                statuses: INTERNAL_SERVER_ERROR
            #                methods: GET
            #                backoff:
            #                  firstBackoff: 10ms
            #                  maxBackoff: 50ms
            #                  factor: 2
            #                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
    discovery:
      client:
        # 静态服务配置，SimpleDiscoveryClient
        simple:
          instances:
            hello-service:
              - uri: http://localhost:8001
                instance-id: s1
              - uri: http://localhost:8002
                instance-id: s2
              - uri: http://localhost:8003
                instance-id: s3

logging:
  level:
    org.springframework.cloud.gateway: TRACE

#resilience4j.circuitbreaker:
#  configs:
#    default:
#      registerHealthIndicator: true
#      slidingWindowSize: 2 # 滑动窗口大小（请求数）
#      failureRateThreshold: 50 # 失败率阈值，2 次内失败率超过 50%，则进入 open 状态
#      waitDurationInOpenState: 5s # open 状态持续时间