server:
  port: 8080

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 2 # 滑动窗口大小（请求数）
      failureRateThreshold: 50 # 失败率阈值，2 次内失败率超过 50%，则进入 open 状态
      waitDurationInOpenState: 5s # open 状态持续时间

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 1s # 超过1s则取消认为请求失败
      cancelRunningFuture: true